name: Chạy bot.py

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Thiết lập Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Cập nhật pip
        run: python -m pip install --upgrade pip

      - name: Cài đặt thư viện telebot
        run: pip install telebot

      - name: Chạy bot.py
        run: python bot.py
